### ISSUE TITLE
Add support for own VPS Server plss

### ISSUE THREAD

**Issue by binnichtaktiv** [bunnykek/MultiUpload#1]
Hi
i want to use this bot on my own VPS server. Can you pls add support? I tired it with heroku but the bot is not responding... Can you help me please

**Comment by bunnykek** [comment]
Easy, Just set all the ENV variables first and run the bot.py

**Comment by erickyun** [comment]
> Easy, Just set all the ENV variables first and run the bot.py

Hello,

I was wondering the same thing sir.
Could you please tell me how can I set all the ENV variables?

Create .env file?
Example like this:

```
authorized_list = ""
bot_token = ""
api_id = ""
api_hash = ""
token_json = ""

**Comment by bunnykek** [comment]
Yup. That should work

**Comment by erickyun** [comment]
I did setup like this.
Im getting this error

```
python3.9 bot.py
token_json ENV error!
Traceback (most recent call last):
  File "/root/MultiUpload/modules/gdrive.py", line 14, in <module>
    creds = Credentials.from_authorized_user_info(json.loads(os.getenv('token_json')), SCOPES)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MultiUpload/bot.py", line 4, in <module>
    from modules.gdrive import gdriveDownload
  File "/root/MultiUpload/modules/gdrive.py", line 18, in <module>
    raise Exception("token_json ENV error!")
Exception: token_json ENV error!
```

```
token_json = "{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}"
authorized_list = "11111"
bot_token = "11111:AAAA"
api_id = "26666"
api_hash = "xxxhshsjsjd"
```

For token_json Should I add like this or should I only add token?

**Comment by erickyun** [comment]
> Yup. That should work

I did uncomment [line 4](https://github.com/bunnykek/MultiUpload/blob/3045c8ca9fae20c3953bac038c2d308f024afd06/bot.py#L4) from bot.py 
The bot starts right now but bot gives `argument of type 'int' is not iterable` error when I execute /start?

**Comment by bunnykek** [comment]
lel, use this 
```
token_json = """{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}"""
```
or
```
token_json = '{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}'
```

**Comment by erickyun** [comment]
> lel, use this
> 
> ```
> token_json = """{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}"""
> ```
> 
> or
> 
> ```
> token_json = '{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}'
> ```

thank you for your response but sadly its not working?
I would appreciate if you could please fix this issue?
https://github.com/bunnykek/MultiUpload/issues/1#issuecomment-1596697985

**Comment by bunnykek** [comment]
> > lel, use this
> > 
> > ```
> > token_json = """{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}"""
> > ```
> > 
> > or
> > 
> > ```
> > token_json = '{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}'
> > ```
> 
> thank you for your response but sadly its not working?
> I would appreciate if you could please fix this issue?
> https://github.com/bunnykek/MultiUpload/issues/1#issuecomment-1596697985

Let me check it in my pc. I will be using windows.

**Comment by erickyun** [comment]
> > > lel, use this
> > > ```
> > > token_json = """{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}"""
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > or
> > > ```
> > > token_json = '{"token": "bu.29fkdkdk", "refresh_token": "3/4444", "token_uri": "https://oauth2.googleapis.com/token", "client_id": "DDDDD", "client_secret": "GGGGG", "scopes": ["https://www.googleapis.com/auth/drive.readonly"], "expiry": "2023-06-19T07:40:36.373953Z"}'
> > > ```
> > 
> > 
> > thank you for your response but sadly its not working?
> > I would appreciate if you could please fix this issue?
> > [#1 (comment)](https://github.com/bunnykek/MultiUpload/issues/1#issuecomment-1596697985)
> 
> Let me check it in my pc. I will be using windows.

Thank you. 
Could you maybe also consider adding sample.env file for VPS users? 

I count on your kind consideration of my request. I appreciate your work sir. 🙏🙂👍

**Comment by bunnykek** [comment]
Fixed some stuffs. Follow these steps to run in WIN/LINUX vps.
- Make the backup of tokens and env variables
- Again git clone the repo
- Follow the [VPS guide](https://github.com/bunnykek/MultiUpload#vps-deploy)

**Comment by erickyun** [comment]
> Fixed some stuffs. Follow these steps to run in WIN/LINUX vps.
> 
> * Make the backup of tokens and env variables
> * Again git clone the repo
> * Follow the [VPS guide](https://github.com/bunnykek/MultiUpload#vps-deploy)

Thank you.
Bot starts right now but when I try to upload TG file I get  `No such file or directory: 'response.json'` error?

`
Bot started                                                       Telegram...                                                       processing TG                                                     Got the message object!                                           video.mp4 1263636
Uploading `video.mp4` to catbox                                                  Usage: go-ul_x64 [--outpath OUTPATH] [--wipe] [--files FILES] [--private] [--template TEMPLATE] [--overwrite] [--user USER] [--directories DIRECTORIES] [--recursive] [--speedlimit SPEEDLIMIT] HOSTS [HOSTS ...]                                                       error: unknown argument -j                                        [Errno 2] No such file or directory: 'response.json'
`

**Comment by bunnykek** [comment]
just create a file named `response.json`

**Comment by erickyun** [comment]
> just create a file named `response.json`

Thanks.
it seems your [go-ul_x64](https://github.com/bunnykek/MultiUpload/raw/main/go-ul_x64) works but it seems [this one](https://github.com/Sorrow446/go-upload/releases/download/3/go-ul_linux_x64) doesn't?
İs this not the latest version? 
I have reported to the owner btw, maybe it will get a fix?

Secondly, I would appreciate if you could you maybe add an progress bar for Download/Upload please? Shall I open new issue for this?

I count on your kind consideration of my request. Thank you for this amazing project I appreciate your work sir. 🙏👍

**Comment by bunnykek** [comment]
The core uploading module is made by someone else, therefore i don't have any control on its functionality.
