### ISSUE TITLE
errors when i run bot.py

### ISSUE THREAD

**Issue by binnichtaktiv** [bunnykek/MultiUpload#2]
I tried it so many times I think im trying for 3 hours now but i get this or this error:

C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main>python3 bot.py
token_json ENV error!
Traceback (most recent call last):
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\modules\gdrive.py", line 14, in <module>
    creds = Credentials.from_authorized_user_info(json.loads(os.getenv('token_json')), SCOPES)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\bot.py", line 4, in <module>
    from modules.gdrive import gdriveDownload
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\modules\gdrive.py", line 18, in <module>
    raise Exception("token_json ENV error!")
Exception: token_json ENV error!

C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main>python3 bot.py
token_json ENV error!
Traceback (most recent call last):
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\modules\gdrive.py", line 14, in <module>
    creds = Credentials.from_authorized_user_info(json.loads(os.getenv('token_json')), SCOPES)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\bot.py", line 4, in <module>
    from modules.gdrive import gdriveDownload
  File "C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main\modules\gdrive.py", line 18, in <module>
    raise Exception("token_json ENV error!")
Exception: token_json ENV error!

C:\Users\jonas\Documents\MultiUpload-main\MultiUpload-main>

**Comment by bunnykek** [comment]
Set the token_json ENV value first

**Comment by bunnykek** [comment]
https://github.com/bunnykek/MultiUpload/issues/1#issuecomment-1603323647
